name: Daily News Editorial

on:
  schedule:
    # 17:00 IST = 11:30 UTC
    - cron: '0 12 * * *'
    # 19:30 IST = 14:00 UTC
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run-editorial:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout full repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Build your Docker image
      - name: Build Docker image
        run: docker build -t news-bot .

      # 3. Install all Python dependencies
      - name: Install Python deps (incl. feedparser)
        run: |
          pip install -r requirements.txt
          pip install feedparser python-dateutil

      # 4. Extract today’s URLs
      - name: Fetch today’s news URLs
        run: python fetch_news_urls.py

      # 5. Run the bot inside the container
      - name: Run validation & draft
        id: run
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -eux

          echo "=== TODAY LINKS ==="
          cat today_links.txt

          ARGS=$(paste -sd' ' today_links.txt)
          echo "=== ARGS Passed to Container: $ARGS ==="

          docker run --rm \
            -v "${{ github.workspace }}:/out" \
            -w /out \
            -e OPENAI_API_KEY \
            news-bot $ARGS

      # 6. Upload everything we expect
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}
          path: |
            today_links.txt
            links.json
            run-summary.json
            editorial.txt

      # 7. Email only if editorial was generated
      - name: Send email (if editorial exists)
        if: success() && hashFiles('editorial.txt') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Daily Hindi Editorial – Run #${{ github.run_number }}"
          to: sureshchouksey8@gmail.com
          from: "News Bot <sureshchouksey8@gmail.com>"
          body_file: editorial.txt
