name: Daily News Editorial

on:
  schedule:
    - cron: '0 12 * * *'   # Daily at ~17:00 IST
    - cron: '30 14 * * *'   # Daily at ~19:30 IST
  workflow_dispatch:

jobs:
  run-editorial:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install runner deps
        run: pip install feedparser python-dateutil

      - name: Fetch today's news URLs
        run: python fetch_news_urls.py

      - name: Require ≥3 links
        run: |
          n=$(wc -l < today_links.txt)
          if [ "$n" -lt 3 ]; then
            echo "❌ Only $n links found."
            exit 1
          fi

      - name: Build Docker image
        run: docker build -t news-bot .

      - name: Generate Editorial
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/out" \
            -e OPENAI_API_KEY \
            news-bot $(cat today_links.txt)

      - name: List files after Docker
        run: |
          echo "Workspace contents:"
          ls -l
          echo "Editorial preview:"
          cat editorial.txt || echo "No editorial.txt found"

      - name: Send email
        if: success() && hashFiles('editorial.txt') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Daily Hindi Editorial – Run #${{ github.run_number }}"
          to: sureshchouksey8@gmail.com
          from: "News Bot <sureshchouksey8@gmail.com>"
          body_file: editorial.txt
