name: Daily News Editorial

on:
  schedule:
    # 17:00 IST = 11:30 UTC
    - cron: '0 12 * * *'
    # 19:30 IST = 14:00 UTC
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run-editorial:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: docker build -t news-bot .

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install feedparser and dateutil
        run: pip install feedparser python-dateutil

      - name: Fetch today’s news URLs
        run: python fetch_news_urls.py

      - name: Run validation + draft (debug)
        run: |
          set -eux
          if [ -s today_links.txt ]; then
            echo "=== TODAY LINKS ==="
            cat today_links.txt
            echo "=== STARTING CONTAINER ==="
            docker run --rm -v ${{ github.workspace }}:/out news-bot $(cat today_links.txt)
          else
            echo "❗ No links found for TODAY"
            exit 1
          fi
          echo "=== WORKSPACE AFTER CONTAINER ==="
          find . -maxdepth 2 -type f -print

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}
          path: |
            links.json
            run-summary.json
            editorial.txt

      - name: Send email (only if editorial exists)
        if: success() && hashFiles('editorial.txt') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Daily Hindi Editorial – Run ${{ github.run_number }}"
          to: sureshchouksey8@gmail.com
          from: "News Bot <sureshchouksey8@gmail.com>"
          body_file: editorial.txt
