name: Daily News Editorial

on:
  schedule:
    # 17:00 IST = 11:30 UTC
    - cron: '0 12 * * *'
    # 19:30 IST = 14:00 UTC
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run-editorial:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Build the Docker image
      - name: Build Docker image
        run: docker build -t news-bot .

      # 3️⃣ Install Python dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Install feedparser & dateutil
      - name: Install feedparser and dateutil
        run: pip install feedparser python-dateutil

      # 5️⃣ Fetch today’s news URLs
      - name: Fetch today’s news URLs
        run: python fetch_news_urls.py

      # 6️⃣ Run the container and produce the draft
      - name: Run validation + draft
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -eux

          echo "=== TODAY LINKS ==="
          cat today_links.txt

          # Read links into a Bash array (one URL per element)
          mapfile -t LINKS < today_links.txt
          echo "Running news-bot for ${#LINKS[@]} links..."

          docker run --rm \
            -v "${{ github.workspace }}:/out" \
            -w /out \
            -e OPENAI_API_KEY \
            news-bot "${LINKS[@]}"

          echo "=== OUTPUT FILES ==="
          find . -maxdepth 2 -type f -print

      # 7️⃣ Upload any generated artifacts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}
          path: |
            links.json
            run-summary.json
            editorial.txt

      # 8️⃣ Send email if we got an editorial
      - name: Send email (only if editorial exists)
        if: success() && hashFiles('editorial.txt') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Daily Hindi Editorial – Run #${{ github.run_number }}"
          to: sureshchouksey8@gmail.com
          from: "News Bot <sureshchouksey8@gmail.com>"
          body_file: editorial.txt
