name: Daily News Editorial

on:
  schedule:
    # 17:00 IST = 11:30 UTC
    - cron:  '0 12 * * *'
    # 19:30 IST = 14:00 UTC
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run-editorial:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install fetch_news dependencies
      - name: Install fetch-news deps
        run: pip install feedparser python-dateutil

      # 3) Fetch RSS links
      - name: Fetch today’s news URLs
        run: python fetch_news_urls.py

      # 4) Ensure at least 3 links
      - name: Require ≥3 links
        run: |
          n=$(wc -l < today_links.txt)
          if [ "$n" -lt 3 ]; then
            echo "❌ Only $n links found."
            exit 1
          fi

      # 5) Build Docker image
      - name: Build news-bot container
        run: docker build -t news-bot .

      # 6) Generate editorial via container
      - name: Generate Hindi editorial
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/out" \
            -e OPENAI_API_KEY \
            news-bot $(cat today_links.txt)

      # 7) Debug the generated file
      - name: Show editorial.txt
        run: |
          echo "=== Files in workspace ==="
          ls -1
          echo "=== editorial.txt content ==="
          cat editorial.txt

      # 8) Email editorial.txt via Python
      - name: Send email via Python SMTP
        if: success() && hashFiles('editorial.txt') != ''
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          python3 - << 'PYCODE'
          import os, smtplib
          from email.mime.text import MIMEText

          HOST = "smtp.gmail.com"
          PORT = 465
          USER = os.getenv("SMTP_USER")
          PASS = os.getenv("SMTP_PASS")

          # Read the editorial
          with open("editorial.txt", encoding="utf-8") as f:
              body = f.read()

          # Build the message
          msg = MIMEText(body, _charset="utf-8")
          msg["Subject"] = f"Daily Hindi Editorial – Run #{os.getenv('GITHUB_RUN_NUMBER')}"
          msg["From"]    = USER
          msg["To"]      = "sureshchouksey8@gmail.com"

          # Send via SMTP SSL
          with smtplib.SMTP_SSL(HOST, PORT) as smtp:
              smtp.login(USER, PASS)
              smtp.send_message(msg)

          print("✅ Email sent successfully.")
          PYCODE
