name: Daily News Editorial

on:
  schedule:
    # 17:00 IST = 11:30 UTC
    - cron: '0 12 * * *'
    # 19:30 IST = 14:00 UTC
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run-editorial:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Build Docker image
      - name: Build Docker image
        run: docker build -t news-bot .

      # 3. Install Python dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # 4. Install feedparser + dateutil
      - name: Install feedparser and dateutil
        run: pip install feedparser python-dateutil

      # 5. Fetch today’s news URLs
      - name: Fetch today’s news URLs
        run: python fetch_news_urls.py

      # 6. Run news-bot with full debug
      - name: Run validation + draft (debug)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -eux

          echo "=== TODAY LINKS ==="
          # Load the URLs into a Bash array
          mapfile -t LINKS < today_links.txt
          printf '%s\n' "${LINKS[@]}"

          echo "=== RUNNING news-bot CONTAINER ==="
          # Mount the repo as /out, cd into /out, pass the URLs, and capture all logs
          docker run --rm \
            -v "${{ github.workspace }}:/out" \
            -w /out \
            -e OPENAI_API_KEY \
            news-bot "${LINKS[@]}" 2>&1 | tee container.log || true

          echo "=== CONTAINER LOGS ==="
          cat container.log

          echo "=== FILES IN WORKSPACE ==="
          find . -maxdepth 2 -type f -print

      # 7. Upload artifacts (including container.log)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}
          path: |
            container.log
            links.json
            run-summary.json
            editorial.txt

      # 8. Send email if editorial exists
      - name: Send email (only if editorial exists)
        if: success() && hashFiles('editorial.txt') != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Daily Hindi Editorial – Run #${{ github.run_number }}"
          to: sureshchouksey8@gmail.com
          from: "News Bot <sureshchouksey8@gmail.com>"
          body_file: editorial.txt
